apiVersion: v1
kind: LimitRange
metadata: 
  name: my-limit-range
  namespace: default
spec:
  limits:
    - default:
        cpu: 0.7
        memory: 500Mi
      defaultRequest:
        cpu: 0.3
        memory: 100Mi
      type: Container