apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-handson-2
  labels:
    env: staging
spec:
  selector:
    matchLabels:
      env: stag
      service: unified-cart
  replicas: 2
  template: 
    metadata:
      name: my-pod-replicas
      labels:
        env: stag
        service: unified-cart
    spec:
      containers:
         - name: json-server
           image: ramit07/simple-json-server 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-handson
  labels:
    env: staging
spec:
  selector:
    matchLabels:
      env: stag
      service: unified-cart
  replicas: 3
  template: 
    metadata:
      name: my-pod-replicas
      labels:
        env: stag
        service: unified-cart
    spec:
      containers:
        - name: nginx-rep
          image: nginx