apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: redis

spec:
  replicas: 4
  selector:
    matchLabels:
      app: busy
  
  template:
    metadata:
      name: hey
      labels:
        app: busy
    spec:
      containers:
        - name: my-con
          image: busybox