apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    env: staging 
spec:
  selector:
    matchLabels:
      env: stag
      service: unified-cart
  replicas: 4
  template: 
    metadata:
      name: my-pod-replicas
      labels:
        env: stag
        service: unified-cart
    spec:
      containers:
        - name: nginx-rep
          image: nginx