apiVersion: v1
kind: Pod
metadata:
  name: backendservice-pod
  labels:
    backend: student-service
spec:
  containers:
    - name: backendservice-container
      image: ramit07/springboot_studentservice_multiarch
      ports:
        - containerPort: 8090
      env:
        - name: db_url
          value: jdbc:postgresql://postgres-db:5432/student_service_db
        - name: db_username
          value: postgres
        - name: db_password
          value: zxcv