apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    db-service: postgres
spec:
  selector:
    db: postgres
    backend: student-service
  ports:
    - port: 5432
      targetPort: 5432
    